name: Build OpenWRT for AX6-IPQ

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/LiBwrt-op/openwrt-6.x.git
  CONFIG_FILE: AX6-IPQ/.config-ipq
  DIY_SH: AX6-IPQ/diy.sh
  FILES: AX6-IPQ/files
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clean disk space (Native & Safe)
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune -a -f || true
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf /var/lib/apt/lists/*
        df -hT

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/nantayo/My-Pkg/master/2305)
        sudo timedatectl set-timezone "$TZ"
        sudo chown -R $USER:$GROUPS $GITHUB_WORKSPACE

    - name: Clone source code
      working-directory: ./
      run: |
        git clone --depth 1 $REPO_URL openwrt

    - name: cache wrt build
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: AX6-IPQ-build
        prefix: ${{ github.workspace }}/openwrt

    - name: Initial feeds setup
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run DIY script
      run: |
        [ -e $FILES ] && cp -r $FILES openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SH

    - name: Link and Refresh feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds install -a

    - name: Load custom config & defconfig
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        cd openwrt
        echo "CONFIG_PACKAGE_luci-app-nikki=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-nikki-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_nikki=y" >> .config
        echo "CONFIG_PACKAGE_mihomo=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-daed=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-daed-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_daed=y" >> .config
        echo "CONFIG_PACKAGE_dae=y" >> .config
        make defconfig

    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s

    - name: Upload all outputs to Actions Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AX6-OpenWRT-Stock-AllFiles
        path: openwrt/bin/targets/qualcommax/ipq807x/
        retention-days: 90
